title: Animes I'm into
description: アニメ / Animes I'm into as of 2024

collections:
  characters:
    output: true
    sort_by: show
    permalink: /:collection/:name

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-paginate

show_downloads: false
google_analytics: G-BTYGFCLRKR
