title: Animes I'm into
description: アニメ / Animes I'm into as of 2024
collections:
  characters:
    output: true
    permalink: /characters/:path/
  shows:
    output: true
    permalink: /shows/:path/

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-relative-links
show_downloads: false
google_analytics: G-BTYGFCLRKR
baseurl: /fandoms
remote_theme: pages-themes/minimal@v0.2.0

