title: Animes I'm into
description: アニメ / Animes I'm into as of 2024
collections:
  characters:
    output: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-relative-links
pagination:
  enabled: true
paginate_path: /page:num
per_page: 3
show_downloads: false
google_analytics: G-BTYGFCLRKR
baseurl: /fandoms/
