title: Animes I'm into
description: アニメ / Animes I'm into as of 2024
collections:
  characters:
    output: true
  shows:
    output: true
  pages:
    output: true
remote_theme: pages-themes/minimal@v0.2.0

defaults:
  - scope:
      path: "/shows/"
      type: "shows"
    values:
      layout: "show"
  - scope:
      path: "/characters/"
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: "/pages/"
      type: "pages"
    values:
      layout: "page"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-relative-links
show_downloads: false
google_analytics: G-BTYGFCLRKR
baseurl: /fandoms
