title: Animes I'm into
description: アニメ / Animes I'm into as of 2024
collections:
  characters:
    output: true
  shows:
    output: true
  pages:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-relative-links
show_downloads: false
google_analytics: G-VH529SPHJW
baseurl: /fandoms
remote_theme: pages-themes/minimal@v0.2.0

